CREATE TABLE [dbo].[Surgery] (
    [SurgeryId]			  INT IDENTITY(1,1),
	[AdmissionDate]		  DATE NOT NULL,
	[Description]		  VARCHAR (200) NOT NULL,
	[SurgeryStart]		  DATETIME NOT NULL,
	[SurgeryEnd]		  DATETIME NOT NULL,
	[Status]			  VARCHAR (10)   NOT NULL,
	[PostOperationMng]    VARCHAR(500) NULL,
	[RegistrationDate]	  DATE NOT NULL,
	[TheatorId]			  VARCHAR(5) NOT NULL,
	[DoctorId]			  VARCHAR(20) NOT NULL,
	[PatientId]			  VARCHAR(20) NOT NULL,
	[WardNo]		      VARCHAR(5) NOT NULL,
	[SurgeonApproval]	  VARCHAR(10) NULL,
	[SurgeonApprover]	  VARCHAR(20) NULL,
	[SurgeonDescription]  VARCHAR(200) NULL,
	[AnesthetistApproval] VARCHAR(10) NULL,
	[AnesthetistApprover] VARCHAR(20) NULL,
	[AnesthetistProlems]  VARCHAR(200) NULL,
	[ModeOfAnesthesia]    VARCHAR(100) NULL,
	[DirectorApproval]    VARCHAR(10) NULL,
	[DirectorApprover]    VARCHAR(20) NULL,
	[DirectorDescription] VARCHAR(200) NULL,
    PRIMARY KEY CLUSTERED ([SurgeryId]),
	CONSTRAINT FK_SurgeryTheator FOREIGN KEY (TheatorId) REFERENCES [Theator](TheatorId),
	CONSTRAINT FK_SurgeryEmployeer FOREIGN KEY (DoctorId) REFERENCES [Employee](EmployeeId),
	CONSTRAINT FK_SurgeryWard FOREIGN KEY (WardNo) REFERENCES [Ward](WardNo)
);